### ISSUE TITLE
Error nonetype object has no attribute 'alliance_name'

### ISSUE THREAD

**Issue by jmchanchong** [fatcat4096/MSF2CSV#12]
I have this error with the new version of the program :

Traceback (most recent call last):
  File "C:\MarvelStrikeForce\msf2csv.py", line 212, in <module>
    main(args.alliance_name, args.prompt, args.headless, force, table_format, args.login) # Just run myself
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MarvelStrikeForce\log_utils.py", line 77, in wrapped_func
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\MarvelStrikeForce\msf2csv.py", line 28, in main
    alliance_info = get_alliance_info(alliance_name, prompt, force, headless, scopely_login)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MarvelStrikeForce\log_utils.py", line 77, in wrapped_func
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\MarvelStrikeForce\process_website.py", line 55, in get_alliance_info
    alliance_info = parse_alliance(driver)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MarvelStrikeForce\log_utils.py", line 77, in wrapped_func
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\MarvelStrikeForce\parse_contents.py", line 26, in parse_alliance
    alliance['name'] = driver.alliance_name
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'alliance_name'

**Comment by fatcat4096** [comment]
Is this resolved?

**Comment by fatcat4096** [comment]
Gracefully exits if user fails to enter valid login/password
