### ISSUE TITLE
msf2csv -c || csv export | receiving error

### ISSUE THREAD

**Issue by akheva** [fatcat4096/MSF2CSV#9]
Traceback (most recent call last):
  File "/home/akheva/Projects/MSF2CSV_IS/msf2csv.py", line 87, in <module>
    main(args.file_or_alliance, args.csv, args.nohist, args.prompt, args.force, args.export_block, args.import_block, args.min_iso, args.min_tier, args.max_others, args.output) # Just run myself
  File "/home/akheva/Projects/MSF2CSV_IS/msf2csv.py", line 42, in main
    write_file(filename+"original.csv", generate_csv(alliance_info))
  File "/home/akheva/Projects/MSF2CSV_IS/generate_csv.py", line 30, in generate_csv
    iso_class = {'S':'Striker','K':'Skirmisher','H':'Healer','F':'Fortifier','R':'Raider'}[alliance_info['members'][player_name]['other_data']['cls']]
KeyError: 'cls'

**Comment by fatcat4096** [comment]
Resolved. Had an issue with mapping encoding of ISO data during output after changing the location of this info in alliance_info / cached_data structure.
